//
// Created by Eric Huiza on 3/26/26.
//

#ifndef EJERCICIO_OPERADORES_CLINICA_ENUMS_H
#define EJERCICIO_OPERADORES_CLINICA_ENUMS_H

enum Especialidad {
    CARDIOLOGIA,
    DERMATOLOGIA,
    NEUROLOGIA,
    PEDIATRIA,
    PSIQUIATRIA,
    TRAUMATOLOGIA,
    ENDOCRINOLOGIA,
    GINECOLOGIA,
    PSICOLOGIA,
    ORTOPEDIA,
    GENERAL
};

enum Estado {
    RESERVADA,
    CANCELADA
};

#endif //EJERCICIO_OPERADORES_CLINICA_ENUMS_H
